package Data;

import Koneksi.Server;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XXxxXX
 */
public class DataPesanan extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataPesanan
     */
    public DataPesanan() {
        initComponents();
        showPesanan();
    }
    
    
    public void showPesanan(){
        DefaultTableModel dataModel =(DefaultTableModel) tabelPesanan.getModel();
        int lengthRow = dataModel.getRowCount();
        for (int n=0; n<lengthRow; n++) {
            dataModel.removeRow(0); 
        }
        try{
            Connection conn = (Connection) Server.serverData();
            Statement st = conn.createStatement();
            String sql = "SELECT id_pembeli, nama_pembeli, nama_menu, harga, total, hargatotal from pesanan ORDER BY id_pesanan ASC";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                dataModel.addRow(new Object [] {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                });
            }
            rs.close();
            st.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    public void editData(){
        try{
            Connection conn = (Connection) Server.serverData();
            Statement st = conn.createStatement();
            int updateHarga = Integer.parseInt(tfJumlah.getText()) * Integer.parseInt(tfHarga.getText());
            String sql = "UPDATE pesanan SET total='"+tfJumlah.getText()+"', hargatotal='"+updateHarga+"'"
                    + "WHERE id_pembeli='"+tfIdPelanggan.getText()+"'";
            st.executeUpdate(sql);
            showPesanan();
            JOptionPane.showMessageDialog(null, "EDIT DATA BERHASIL ");
            st.close();
        }catch ( Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    public void hapusData(){
        try{
            Connection conn = (Connection) Server.serverData();
            Statement st = conn.createStatement();
            String sql = "DELETE FROM pesanan where id_pembeli='"+tfIdPelanggan.getText()+"'";
            st.executeUpdate(sql);
            showPesanan();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS");
            st.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    public void cariPesanan(){
        DefaultTableModel dataModel =(DefaultTableModel) tabelPesanan.getModel();
        int lengthRow = dataModel.getRowCount();
        for (int n=0; n<lengthRow; n++) {
            dataModel.removeRow(0); 
        }
        try{
            Connection conn = (Connection) Server.serverData();
            Statement st = conn.createStatement();
            String sql = "SELECT id_pembeli, nama_pembeli, nama_menu, harga, total, hargatotal from pesanan where nama_pembeli like '%"+jTextField1.getText()+"%'";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                dataModel.addRow(new Object [] {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)        
                });
            }
            rs.close();
            st.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    
    public void clearField(){
        tfIdPelanggan.setText("");
        tfPemesan.setText("");
        tfMenu.setText("");
        tfHarga.setText("");
        tfJumlah.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataPesanan = new javax.swing.JPanel();
        txtJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPesanan = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfPemesan = new javax.swing.JTextField();
        tfMenu = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfIdPelanggan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        panelDataPesanan.setBackground(new java.awt.Color(204, 204, 204));

        txtJudul.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtJudul.setText("DAFTAR PESANAN");

        tabelPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pelanggan", "Nama Pemesan", "Menu Pesanan", "Harga Menu", "Jumlah Pesan", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelPesananMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPesanan);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Pemesan");

        jLabel3.setText("Menu Pesanan");

        jLabel4.setText("Harga Menu");

        jLabel6.setText("Jumlah");

        tfPemesan.setEditable(false);

        tfMenu.setEditable(false);

        tfHarga.setEditable(false);

        jLabel7.setText("Id_Pelanggan");

        tfIdPelanggan.setEditable(false);

        jLabel1.setText("Ketik Nama Pemesan Untuk Mencari Pesanan");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelDataPesananLayout = new javax.swing.GroupLayout(panelDataPesanan);
        panelDataPesanan.setLayout(panelDataPesananLayout);
        panelDataPesananLayout.setHorizontalGroup(
            panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataPesananLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtJudul)
                .addGap(277, 277, 277))
            .addGroup(panelDataPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataPesananLayout.createSequentialGroup()
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(58, 58, 58)
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPemesan)
                            .addGroup(panelDataPesananLayout.createSequentialGroup()
                                .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(panelDataPesananLayout.createSequentialGroup()
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelDataPesananLayout.setVerticalGroup(
            panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataPesananLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtJudul)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataPesananLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(btnEdit))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(panelDataPesananLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDataPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDataPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        if (tfIdPelanggan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harap Pilih Data Yang Akan Diubah !");
        }else{
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Akan Mengubah Data Ini ?", "KONFIRMASI", YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION)  {
                editData();
                clearField();
            }else{
                clearField();
                JOptionPane.showMessageDialog(null, "Data Tidak Jadi Diubah");
            }
        }
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelPesananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPesananMousePressed
        // TODO add your handling code here:
        
        int row = tabelPesanan.rowAtPoint(evt.getPoint());
        tfIdPelanggan.setText(tabelPesanan.getValueAt(row, 0).toString());
        tfPemesan.setText(tabelPesanan.getValueAt(row, 1).toString());
        tfMenu.setText(tabelPesanan.getValueAt(row, 2).toString());
        tfHarga.setText(tabelPesanan.getValueAt(row, 3).toString());
        tfJumlah.setText(tabelPesanan.getValueAt(row, 4).toString());

    }//GEN-LAST:event_tabelPesananMousePressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        if (tfIdPelanggan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harap Pilih Data Yang Akan Diubah !");
        }else{
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Akan Menghapus Data Ini ?", "KONFIRMASI", YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION)  {
                hapusData();
                clearField();
            }else{
                clearField();
                JOptionPane.showMessageDialog(null, "Data Tidak Jadi Dihapus");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        
        if (!"".equals(jTextField1.getText())) {
            cariPesanan();
        } else {
            showPesanan();
        }
    }//GEN-LAST:event_jTextField1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelDataPesanan;
    private javax.swing.JTable tabelPesanan;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfIdPelanggan;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfMenu;
    private javax.swing.JTextField tfPemesan;
    private javax.swing.JLabel txtJudul;
    // End of variables declaration//GEN-END:variables
}
